### ISSUE TITLE
URL datatype does not provide link to external URL

### ISSUE THREAD

**Issue by sleupold** [DNNCommunity/DNN.FormAndList#65]
## Describe the bug
If you use a column of data type "URL", enable "Track Number of Downloads" and add a row with an http or https link, the link is properly displayed in caption but the link simply contains current page address.

## To Reproduce
1. Add FnL to a page 
2. Add a column of type "URL" and enable checkbox Track Number of Downloads.
   Save (without entering a value for caption) 
3. Add a record with an URL like "http://www.github.com" and save
4. See the url properly displayed, but when you click it, it just reloads the current page.

## Expected behavior
you are forwarded to the displayed page

## Error log
non

## Additional context
variables file and file_UDT_URL in XML view are not properly populated (blanks added):

< File>
< !--https://www.github.com-->< a href="">https://www.github.com< /a>
< /File>

**Comment by SCullman** [comment]
@sleupold , thank you for reporting!
Do you want to try to fix the issue? 🙏 Of course I can help you along the way, but most of the code and concepts should still be familiar to you.

**Comment by sleupold** [comment]
@SCullman atm i am not sure, whether it is a FnL issue or a feature ripped out of DNN platform. Still investigating.

**Comment by SCullman** [comment]
@sleupold I am quite sure it is a bug.
[See here](https://github.com/DNNCommunity/DNN.FormAndList/blob/939462cf7cd9aaf449f98342e8dee9b4cd08f238/DataTypes/URL.cs#L368), url is unmodified (and just empty) if it is set to Url  *and* tracking.
And there are no extra actions taken for any other link type to enable tracking.

**Comment by sleupold** [comment]
@SCullman other data types are using linkclick.aspx handler, but do not count clicks either.
I am travelling atm, will have a look nect but one week.
PS: I encountered the issue, while trying to support another community member.

**Comment by SCullman** [comment]
Well, this is fixed. But shouldn't the download number appear anywhere? I cannot remember.

**Comment by SCullman** [comment]
Ok, with DataType `LookUp` and token `[File:Clicks]`.
The urlController is always [initialized with false](https://github.com/DNNCommunity/DNN.FormAndList/blob/76260af26f0de13992619b56d92fc7d1aeb69179/DataTypes/URL.cs#L133) , as  the setting `URLDownloadTracking`is not set anywhere, AND it should be controlled by the proper field setting.

**Comment by vmasanas** [comment]
I have a similar issue if you just select a file, not a url.
In this case a link limilar to this is generated:

<Document_UDT_Url>/LinkClick.aspx?fileticket=ORvcmU6B_Us%3d&amp;tabid=3708&amp;portalid=0&amp;mid=10056</Document_UDT_Url>

The problem is that on DotNetNuke.Services.FileSystem.FileServerHandler, line 71 this will not correctly identify the mid or tabid parameters so any tracking fill fail.
 
 if (context.Request.QueryString["mid"] != null)
                {
                    Int32.TryParse(context.Request.QueryString["mid"], out ModuleId);
                }

BTW, if you select a File, not a URL, should not it also ask for tracking?

**Comment by SCullman** [comment]
It's starting to feel like a family reunion here.
 
* The link was html encoded, which makes no sense and breaks any following querystring parms.
* If the type is URL, it should never ask for tracking. But it should do for type download.

**Comment by SCullman** [comment]
New release 6.5.4 available for testing.
@sleupold , @vmasanas Thank you for reporting and commenting, is was indeed helpful.

**Comment by vmasanas** [comment]
@SCullman I installed the new version of the module but I still see the url has the same format as before.
The link I see there is 
..../LinkClick.aspx?fileticket=jbdt2JJoHbA%3d&amp;tabid=3708&amp;portalid=0&amp;mid=10056

am I missing something here?

**Comment by SCullman** [comment]
@vmasanas Can't reproduce. I see links like
`/LinkClick.aspx?fileticket=wX7FnQbzE18%3d&tabid=33&portalid=0&mid=381&language=en-US`
And I double checked and verified  that the correct assembly (tagged with fileversion 6.5.4) is both in my bin and in [release](https://github.com/DNNCommunity/DNN.FormAndList/releases/tag/06.05.04).

Btw, if you test with old data:  
* Ensure `Track Number of Downloads` is enabled for the filed of type `url`
* You need to edit and save the row, otherwise the file/ url is not regstered for tracking.
