### ISSUE TITLE
Integer and String types with lookup "caption|value" lists do not display the caption

### ISSUE THREAD

**Issue by sleupold** [DNNCommunity/DNN.FormAndList#7]
if you provide a text value list for a text or integer column like "caption1|value1,caption2|value2", the caption is displayed in edit form, but not in grid and XSL rendered list and detail views. The system should generate an extra column [name_UDT_value] to provide the value and [Name] should provide the caption.

**Comment by SCullman** [comment]
It is correct that the value is displayed in grid and XSLT and should remain as the default behavior.
If you really need the caption, add a calculated column or add a template in XSLT.
The main purpose of this feature was to to streamline the output in table mode. A change might break these usecases.
I recommend to close tis issue and don't touch it at all!

**Comment by valadas** [comment]
I agree the default behaviour should not change in order to not break existing implementations.
What about doing like for images, where you have the value in the standard table but you have the separate pieces in the XML, we could do the same for lists, leave the value as is and add [name_UDT_caption] in the generated XML if people want to use that in a XSLT script?

Any toughts on this @sleupold and @DNNCommunity/module-dev-team

**Comment by valadas** [comment]
I am closing this issue in the spirit of cleaning the backlog since nobody provided a PR for it after many years
